Dataset: Tsanas, A. & Xifara, A. (2012). Energy Efficiency [Dataset]. UCI Machine Learning Repository. https://doi.org/10.24432/C51307.

In [ ]:
import pandas as pd
import numpy as np 
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("energy_data.csv")

In [ ]:
df.head()

     X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28

In [ ]:
df.isna().sum().sum()

np.int64(0)

In [ ]:
columnNames = ["Relative Compactness", "Surface Area", "Wall Area", "Roof Area", "Overall Height", "Orientation", "Glazing Area", "Glazing Area Distribution", "Heating Load", "Cooling Load"]
df.columns = columnNames
df.head()

,Relative Compactness,Surface Area,Wall Area,Roof Area,Overall Height,Orientation,Glazing Area,Glazing Area Distribution,Heating Load,Cooling Load
0,0.98,514.5,294.0,110.25,7.0,2,0.0,0,15.55,21.33
1,0.98,514.5,294.0,110.25,7.0,3,0.0,0,15.55,21.33
2,0.98,514.5,294.0,110.25,7.0,4,0.0,0,15.55,21.33
3,0.98,514.5,294.0,110.25,7.0,5,0.0,0,15.55,21.33
4,0.90,563.5,318.5,122.50,7.0,2,0.0,0,20.84,28.28

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Relative Compactness       768 non-null    float64
 1   Surface Area               768 non-null    float64
 2   Wall Area                  768 non-null    float64
 3   Roof Area                  768 non-null    float64
 4   Overall Height             768 non-null    float64
 5   Orientation                768 non-null    int64
 6   Glazing Area               768 non-null    float64
 7   Glazing Area Distribution  768 non-null    int64
 8   Heating Load               768 non-null    float64
 9   Cooling Load               768 non-null    float64
dtypes: float64(8), int64(2)
memory usage: 60.1 KB

In [ ]:
X = df.iloc[:,:-2]
y1 = df.iloc[:,-2]
y2 = df.iloc[:,-1]

X_train, X_test, y_train1, y_test1, y_train2, y_test2 = train_test_split(X, y1, y2, test_size=0.3, random_state=42)
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [ ]:
models = {
    "Linear Regression": LinearRegression(),
    "Polynomial Regression": make_pipeline(PolynomialFeatures(degree=2), LinearRegression()),
    "Random Forest": RandomForestRegressor(n_estimators=100),
    "SVR": SVR(C=100)
}

In [ ]:
for name, model in models.items():
    model.fit(X_train, y_train1)
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test1, y_pred)
    r2 = r2_score(y_test1, y_pred)
    print(f"model: {name}, mean squared error: {mse:.4f}, R²: {r2:.4f}")

model: Linear Regression, mean squared error: 9.5089, R²: 0.9062
model: Polynomial Regression, mean squared error: 7992.2946, R²: -77.8219
model: Random Forest, mean squared error: 15.2937, R²: 0.8492
model: SVR, mean squared error: 5.2568, R²: 0.9482

Ranking:
1. SVR -> lowest MSE, highest R^2
2. Linear Regression 
3. Random Forest
4. Polynomial Regression -> overfitting

In [ ]:
for name, model in models.items():
    model.fit(X_train, y_train2)
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test2, y_pred)
    r2 = r2_score(y_test2, y_pred)
    print(f"model: {name}, mean squared error: {mse:.4f}, R²: {r2:.4f}")

model: Linear Regression, mean squared error: 11.1456, R²: 0.8764
model: Polynomial Regression, mean squared error: 14994.5166, R²: -165.3497
model: Random Forest, mean squared error: 9.3104, R²: 0.8967
model: SVR, mean squared error: 6.4962, R²: 0.9279

Ranking:
1. SVR -> lowest MSE, highest R²
2. Random Forest
3. Linear Regression
4. Polynomial Regression -> overfitting